### ISSUE TITLE
Human trafficking U.S. Department of Health & Human Services Administration for Children & Families

### ISSUE THREAD

**Issue by Snekili** [official-inquiries/official-inquiries#23]
http://www.acf.hhs.gov/programs/endtrafficking/programs/rescue-and-restore

http://www.humantrafficking.org/organizations/376

https://ovc.ncjrs.gov/humantrafficking/plan.html

http://www.ovc.gov/pubs/FederalHumanTraffickingStrategicPlan.pdf

**Comment by GregoryRhysEvans** [comment]
I'm not sure this is actually an inquiry; it looks more like an action plan.
